stages:
  - test
  - build

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
    - when: never

.backend-base:
  image: python:3.12
  stage: test
  variables:
    UV_CACHE_DIR: ".uv-cache"
  cache:
    key:
      files:
        - pyproject.toml
        - uv.lock
    paths:
      - .uv-cache/
  before_script:
    - pip install uv
    - uv sync --all-groups --frozen

backend:ruff:
  extends: .backend-base
  script:
    - uv run ruff check .

backend:mypy:
  extends: .backend-base
  script:
    - uv run mypy .

backend:pytest:
  extends: .backend-base
  script:
    - uv run pytest

# Проверки фронтенда
frontend:lint:
  image: node:20
  stage: test
  cache:
    key:
      files:
        - frontend/package-lock.json
    paths:
      - frontend/.npm/
  before_script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run lint

frontend:build:
  image: node:20
  stage: build
  cache:
    key:
      files:
        - frontend/package-lock.json
    paths:
      - frontend/.npm/
  before_script:
    - cd frontend
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run build